theme: jekyll-theme-architect
title: ![Oceanography for Everyone logo](OfE_sticker2.jpg)
description: Developing low-cost, open-source oceanographic hardware for researchers, educators, and ocean stakeholders.
