theme: jekyll-theme-slate
title: Oceanography for Everyone
description: Developing low-cost, open-source oceanographic hardware for researchers, educators, and ocean stakeholders.
show downloads: true
